APP_NAME    := widgets
SRCS        := widgets.c \
               ../../lvgl/demos/lv_demos.c \
               ../../lvgl/demos/widgets/lv_demo_widgets.c \
               ../../lvgl/demos/widgets/lv_demo_widgets_analytics.c \
               ../../lvgl/demos/widgets/lv_demo_widgets_components.c \
               ../../lvgl/demos/widgets/lv_demo_widgets_profile.c \
               ../../lvgl/demos/widgets/lv_demo_widgets_shop.c \
               ../../lvgl/demos/widgets/assets/img_lvgl_logo.c \
               ../../lvgl/demos/widgets/assets/img_clothes.c \
               ../../lvgl/demos/widgets/assets/img_demo_widgets_avatar.c \
               ../../lvgl/demos/widgets/assets/img_demo_widgets_needle.c
LV_SURFACE := 1
include ../../sdk/hb_app.mk
